image: node:latest

stages:
  - deploy

production_deployment:
  stage: deploy
  before_script:
    - npm config set prefix /usr/local
    - npm install -g serverless
    - FAILURE_MESSAGE="Must define \$AWS_ACCESS_KEY_ID and \$AWS_SECRET_ACCESS_KEY. Add keys to $CI_PROJECT_URL/-/settings/ci_cd"
    - test -z "$AWS_SECRET_ACCESS_KEY" && echo $FAILURE_MESSAGE && exit 1
    - test -z "$AWS_ACCESS_KEY_ID" && echo $FAILURE_MESSAGE && exit 1
  script:
    - npm install
    - serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY
    - npm run deploy -- --stage api --region $AWS_DEFAULT_REGION --verbose
  only:
    - master
  environment: production